{{- if .Values.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "sample-app.fullname" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes:
    - {{ .Values.persistentVolume.accessMode }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}
{{- end }}
