apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-app.fullname" . }}-env-secrets
type: Opaque
data:
  {{- range $key, $val := .Values.secretData }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
